### ISSUE TITLE
KITTI Dataset Configuration

### ISSUE THREAD

**Issue by wangzihanggg** [BIT-MJY/CVTNet#15]
Is it possible to provide a configuration for this issue on the KITTI dataset? This is very important for my experiments. Thank you very much for your open-source work.

**Comment by JerryGua** [comment]
> Is it possible to provide a configuration for this issue on the KITTI dataset? This is very important for my experiments. Thank you very much for your open-source work.

你在KITTI数据集上测试成功了吗？

**Comment by JerryGua** [comment]
我的问题已经解决，感谢您的回复！
祝科研工作顺利！



---Original---
From: "Junyi ***@***.***&gt;
Date: Tue, Jun 4, 2024 09:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BIT-MJY/CVTNet] KITTI Dataset Configuration (Issue #15)




 
Hi @wangzihanggg and @JerryGua  I am busy with my new research topic. You can first try the pipeline for KITTI in OT. Your patience is appreciated~

**Comment by allenzg** [comment]
@JerryGua 你在kiiti上测试成功了，方便交流联系一下吗，或者分享一下KITTI的数据集的处理方式

**Comment by BIT-MJY** [comment]
Thanks to @Grandzxw and you can try to use CVTNet on KITTI now. Please pull the newest version.

**Comment by allenzg** [comment]
Hello Dr. Ma, I have recently read your masterpiece "CVTNet: A Cross View Transformer Network for LiDAR Based Place Recognition in Autonomous Driving Environments" and found the code in your link to study it. Thank you for your support! But there is another issue: I am currently unable to reproduce the corresponding indicators of the KITTI dataset. Can you provide a pre-trained model of the KITTI dataset, or are there other ways to reproduce it? May I ask if it is convenient to provide the source code and dataset of this specific work so that we can reference and learn from your work. If convenient, I hope to find a classmate responsible for this job for further consultation. Thank you very much for your reply and answer!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BIT-MJY/CVTNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BIT-MJY/CVTNet] KITTI Dataset Configuration (Issue #15)





 
Thanks to @Grandzxw and you can try to use CVTNet on KITTI now. Please pull the newest version.
