### ISSUE TITLE
What threshold to keep positive place recognitions

### ISSUE THREAD

**Issue by JzHuai0108** [BIT-MJY/CVTNet#5]
Dear Authors,

Thank you for the great work and the open sourcing effort.

We tried to use the descriptors computed by overlaptransformer in our SLAM pipeline to find position loop closures. The knn in faiss always returns the top match (and its distance) for a descriptor, apparently there are a lot of false positives. So the problem is how to discard the bad ones and only keep the good ones. Do we use a fixed threshold for this purpose?

But when we look at the distances computed in the example tests, we find that the distribution of distances of positive matches and the distribution of distances of negative matches largely overlap.
That is, a fixed threshold does not work in this case. So I wonder what criteria we should use to tell positive place recognitions given the descriptors?

Regards,

**Comment by BIT-MJY** [comment]
Hi @JzHuai0108 ,

Thanks for using our code and your effort to integrate it to your SLAM system! Firstly please make sure a reasonable fine-tuning for OT to make the model recognize positive loops powerfully. Secondly,

```
That is, a fixed threshold does not work in this case
```

you are right.  Fixing the threshold is not suggested in place recognition metrics since it can always find the most similar places without the unified similarity scale. So we think you can use a simple way such as the following icp to get the matching score to find the best match in all the top candidates which always contains the best one. You could directly use range-image-based icp to achieve this.

Btw, our CVTNet in this repo has better precision in recognition than OT also with not bad real-time performance, which can also be easily integrated to the SLAM pipeline since the C++ demo has been released.

**Comment by JzHuai0108** [comment]
Sounds reasonable. I agree. We will try CVTNet later on. Thank you for the reply.

**Comment by ynma-hanvo** [comment]
> Hi @JzHuai0108 ,
> 
> Thanks for using our code and your effort to integrate it to your SLAM system! Firstly please make sure a reasonable fine-tuning for OT to make the model recognize positive loops powerfully. Secondly,
> 
> ```
> That is, a fixed threshold does not work in this case
> ```
> 
> you are right. Fixing the threshold is not suggested in place recognition metrics since it can always find the most similar places without the unified similarity scale. So we think you can use a simple way such as the following icp to get the matching score to find the best match in all the top candidates which always contains the best one. You could directly use range-image-based icp to achieve this.
> 
> Btw, our CVTNet in this repo has better precision in recognition than OT also with not bad real-time performance, which can also be easily integrated to the SLAM pipeline since the C++ demo has been released.

hi,  as you mentioned doing ICP for best matches,  is it possible that the 6 DOF  transformation can also be computed from ICP. thanks a lot
